# Generated by Django 4.1.3 on 2023-12-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_etxt',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_etxt',
            new_name='question_text',
        ),
    ]
