# Generated by Django 4.1.3 on 2023-12-30 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_questionchoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionChoice',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.choice'),
        ),
    ]
